version: '3'

services:
  camera:
    build: .
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    network_mode: host